LOG_DIR: './exps'
SEED: 100
EVAL_PATH: "./tmp/ckpts/epoch=0-step=999.ckpt"
TRAINER:
  MODEL_NAME: PointNet_Transformer
  MODEL:
    regression: True
    OBJ_ENCODER:
      TYPE: "pointnet"
      feat_dim: 53
      hidden_size: &hidden 768
    ROOM_ENCODER:
      room_compass_chunks: &num_chunks 12
    JOINT_ENCODER:
      pretrained_emb: True
      num_layers: 6
      num_heads: 12
      hidden_size: *hidden
      dim_feedforward: 3076
      mlm_ratio: 0.1

  
  EPOCHS: 50
  EVAL_INTERVAL: 500

DATASET:
  NAME: MLNv1_Dis_Dataset_Cached
  annt_root: './dset_gen/generated/merged/{split}'
  target_type: 'both'
  ndtw_weight: 0.5

  EVAL:
    NAME: "val_seen"
    batch_size: 32
    num_workers: 8

  TEST:
    NAME: "val_seen"
    batch_size: 32
    num_workers: 8

  TRAIN: 
    NAME: "val_seen"
    batch_size: 32
    num_workers: 8
