LOG_DIR: './exps'
SEED: 100
TRAINER:
  MODEL_NAME: PointNet_Transformer
  MODEL:
    OBJ_ENCODER:
      TYPE: "pointnet2"
      feat_dim: 53
      hidden_size: &hidden 768
    ROOM_ENCODER:
      room_compass_chunks: &num_chunks 12
    JOINT_ENCODER:
      num_layers: 6
      num_heads: 12
      hidden_size: *hidden
      dim_feedforward: 2048

  
  EPOCHS: 50

DATASET:
  NAME: MLNv1_Dis_Dataset_Cached
  annt_root: '/data/leuven/335/vsc33595/ProjectsVSC/DisMLN/dset_gen/generated/cache_sample/{split}'

  EVAL:
    NAME: "valid"
    batch_size: 32
    num_workers: 8

  INFERENCE: "tmp"

  TRAIN: 
    NAME: "train"
    batch_size: 20
    num_workers: 8
