LOG_DIR: './exps'
SEED: 100
TRAINER:
  MODEL_NAME: PointNet_Transformer
  MODEL:
    OBJ_ENCODER:
      TYPE: "pointnet2"
      feat_dim: 53
      hidden_size: &hidden 768
    ROOM_ENCODER:
      room_compass_chunks: &num_chunks 12
    JOINT_ENCODER:
      num_layers: 6
      num_heads: 12
      hidden_size: *hidden
      dim_feedforward: 2048

  
  EPOCHS: 50


DATASET:
  NAME: MLNv1_Dis_Dataset
  annt_root: '/data/leuven/335/vsc33595/ProjectsVSC/DisMLN/dset_gen/samples/{split}'
  map_path: 'data/maps/gmap_floor1_mpp_0.05_channel_last_with_bounds'
  max_num_points: 50
  room_compass_chunks: *num_chunks

  EVAL:
    NAME: "valid"
    batch_size: 16
    num_workers: 8

  INFERENCE: "tmp"

  TRAIN: 
    NAME: "train"
    batch_size: 16
    num_workers: 8
